jogo.bd = 
[
["GRAVIDADE","Força resultante da distorção do espaço-tempo?",0],
["MOLÉCULA","Entidade eletricamente neutra com pelo menos dois átomos.",0],
["HEMOGLOBINA","Transporta o elemento Ferro no corpo humano.",0],
["DETERGENTE","Torna o meio apolar parcialmente polar quando é adicionado.",0],
["CATALISADOR","Substância que faz aumentar a velocidade de uma reação química, mas que não é consumida durante o processo",0],
["DESIDRATAÇÃO","Processo pelo qual se remove água de uma molécula",0],
["ENDOTÉRMICO","Absorve calor",0],
["ENTROPIA","Desordem em uma reação",0],
["EQUILÍBRIO","Velocidade da reação direta é igual à da geação inversa",0],
["EXOTERMICO","Liberação de calor em uma reação química",0],
["HIDROCARBONETO","Composto que contem apenas carbono e hidrogênio",0],
["HOMOGÊNEO","Sistema no qual todos os reagentes estão dissolvidos em solução",0],
["ISÓTOPO","Mesmo numero de prótons mas diferente número de nêutrôns",0],
["ISÓTOPO","Átomos de um mesmo elemento químico que variam de número de massa",0],
["IÔNICA","Ligação química em que ocorre transferência de elétrons",0],
["IÔNICA","Ligação química entre um elemento classificado como metal (cátion) e um ametal (ânion)",0],
["COVALENTE","Ligação química em que ocorre o compartilhamento de elétrons",0],
["ORBITAL","Região onde há a mior probabilidade de se encontrar o elétron",0],
["POLÍMERO","Molécula grande, constituída por unidades repetidas de moléculas menores.",0],
["PURAS","Substâncias que contém um só componente",0],
["HOMOGÊNEA","Mistura em que os componentes se encontram na mesma fase",0],
["ALCANO","Hidrocarboneto cujas moléculas têm uma ou mais ligações simples",0],
["HETEROGÊNEA","Mistura na qual os componentes em duas ou mais fases",0],
["SOLUÇÃO","Mistura homogênea de dois componentes ",0],
["SOLUTO","Componente de uma solução que é dissolvido pelo solvente",0],
["MOLÉCULA","Partícula electricamente neutra em que dois ou mais átomos se encontram ligados por intermédio de ligações covalentes",0],
["FORTE","Ácido que, em solução aquosa, se ioniza na sua totalidade (ou quase); é um bom dador de protões",0],
["FRACO","Ácido pouco ionizante em solução aquosa",0],
["DENSIDADE","Razão entre a massa e o volume de um corpo.",0],
["DESTILAÇÃO","Processo de separação dos componentes de uma mistura líquida homogénea, com diferentes pontos de ebulição",0],
["ALCINO","Hidrocarboneto cujas moléculas têm uma ou mais ligações triplas",0],
["ALCENO","Hidrocarboneto cujas moléculas têm uma ou mais ligações duplas",0],
["ALCOOL","Composto orgânico cujas moléculas contêm o grupo -OH ligado a um átomo de carbono",0],
["ALDEÍDO","Composto orgânico cujas moléculas contêm o grupo -CH=O",0],
["AMINA","Composto orgânico cujas moléculas contêm o grupo -NH2,-NHR ou -NR2",0],
["QUALITATIVA","Análise de uma amostra para determinar a identidade dos elementos, iões ou compostos que estão presentes","Tal Pessoa"],
["QUANTITATIVA","Análise de uma amostra para determinar as proporções em que se encontram presentes os diversos componentes","Tal Pessoa"],
["ANFÓTERO","Substância que pode reagir como ácido ou como base","Tal Pessoa"],
["ÂNION","Ion com carga negativa","Tal Pessoa"],
["FORTE","Base que, em solução aquosa, se dissocia na sua totalidade (ou quase)","Tal Pessoa"],
["CALORÍMETRO","Aparelho usado para determinar o calor de uma reação","Tal Pessoa"],
["AROMÁTICO","Composto orgânico cujas moléculas contêm pelo menos um anel benzênico","Tal Pessoa"],
["CONDENSAÇÃO","Transformação física que consiste na passagem de uma substância do estado gasoso ao estado líquido","Tal Pessoa"],
["EBULIÇÃO","Transformação física que consiste na passagem de uma substância do estado líquido ao estado gasoso, ocorrendo por intervenção de uma fonte de calor.","Tal Pessoa"],
["ELETRÓLISE","Transformação química (reacção redox) provocada por corrente elétrica","Tal Pessoa"],
["ELETRÓLITO","Conduz corrente eléctrica quando se encontra no estado líquido ","Tal Pessoa"],
["IONIZAÇÃO","Energia necessária para remover um elétron de um átomo","Tal Pessoa"],
["EVAPORAÇÃO","Transformação física que ocorre lentamente à temperatura ambiente e que consiste na passagem de uma substância do estado líquido ao estado gasoso.","Tal Pessoa"],
["FÓRMULA QUÍMICA","Notação usada pelos químicos para representar as substâncias","Tal Pessoa"],
["FOTOSSÍNTESE","Transformação química que ocorre por ação da luz e através da qual as plantas com clorofila podem sintetizar a sua matéria orgânica","Tal Pessoa"],
["FUSÃO","Fenômeno físico que consiste na passagem de uma substância do estado sólido ao estado líquido, por absorção de calor","Tal Pessoa"],
["GRUPO","Linha vertical na Tabela Periódica","Tal Pessoa"],
["METAIS ALCALINOS","Constituem o 1º grupo da Tabela Periódica","Tal Pessoa"],
["NEUTRALIZAÇÃO","Reação entre um ácido e uma base resultando em um sal e água","Tal Pessoa"],
["NÚMERO DE AVOGADRO","Número de partículas existentes numa mole (6,02 x 10 23 partículas)","Tal Pessoa"],
["PERÍODO", "Linha horizontal na Tabela Periódica.","Tal Pessoa"]
];
